config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	post 'login' => 'sessions#create'
	delete 'sessions/:id' => 'sessions#destroy', as: 'logout' 
	

		resources :users, controller: "users", :except => [:index, :new, :edit, :create, :show], path: '/' do 
			resources :scavenger_hunts, controller: "scavenger_hunt", :only => [:index, :show, :destroy, :delete]
		end
		resources :hunts, controller: "hunts" do
				    resources :clues
		end

	post 'users/new' => 'users#create', as: 'sign_up'
	get ':id/edit' => 'users#edit', as: "edit_profile"
	get ':id' => 'users#show', as: 'profile'
	post "/:user_id/hunts/:hunt_id/new" => "scavenger_hunt#create", as: 'start_new_hunt'

end

app/models/clue.rb
class Clue < ActiveRecord::Base
  validates_presence_of :description, :longitude, :latitude, :answer	
  belongs_to :hunt


end

app/models/hunt.rb
class Hunt < ActiveRecord::Base
  
  validates_presence_of :description, :longitude, :latitude

  belongs_to :user
  has_many :clues, dependent: :destroy
  has_many :scavenger_hunts, dependent: :destroy

end

app/models/scavenger_hunt.rb
class ScavengerHunt < ActiveRecord::Base
  belongs_to :user
  belongs_to :hunt
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates_presence_of :first_name, :last_name, :username, :email, :password, :on => :create
	validates :username, :uniqueness => true, :length => { :in => 3..20}
	validates :email, :uniqueness => true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

	has_many :hunts
	has_many :scavenger_hunts

	def to_param
		username
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include UsersHelper
	include HuntsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :null_session
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  include UsersHelper
  include SessionsHelper
  def create
    redirect_to root_path unless valid_user_check
  end

  def new
    redirect_to root_path unless valid_user_check
  end

  def edit
    redirect_to root_path unless valid_user_check
  end

  def show
    redirect_to root_path unless valid_user_check
  end

  def update
    redirect_to root_path unless valid_user_check
  end

  def destroy
    redirect_to root_path unless valid_user_check
  end
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
  include UsersHelper
  include SessionsHelper
  def edit
      redirect_to root_path unless valid_user_check
  end

  def show
    if valid_user_check
      @hunt = Hunt.find_by(id: params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    valid_user_check
  end

  def index
    if valid_user_check
        @hunts = Hunt.where.not(user_id: current_user.id)
    else
        redirect_to root_path
    end
  end

  def create
    redirect_to root_path unless valid_user_check
  end

  def new
    redirect_to root_path unless valid_user_check
  end

  def my_hunts
    redirect_to root_path unless valid_user_check
  end
end

app/controllers/scavenger_hunt_controller.rb
class ScavengerHuntController < ApplicationController
  include UsersHelper
  include SessionsHelper
  def show
  		redirect_to root_path unless valid_user_check
      @hunt = ScavengerHunt.find(params[:id]).hunt
  end

  def destroy
  		redirect_to root_path unless valid_user_check
  end

  def create
      p params
      current_user.scavenger_hunts.create(hunt_id: params[:hunt_id])
      redirect_to root_path
  end

  def index
      @user_scav_hunts = current_user.scavenger_hunts
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include UsersHelper
  include SessionsHelper
  def create
  	user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
    		log_in user
    		redirect_to profile_path(user)
    else
    		redirect_to root_path
    end  		
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  include SessionsHelper

  def create
      new_user_params = params[:new_user]

      if new_user_params[:password] == new_user_params[:confirm_password]
        user =  User.new(first_name: new_user_params[:first_name],
                          last_name: new_user_params[:last_name],
                          username: new_user_params[:username],
                          email: new_user_params[:email],
                          password: new_user_params[:password])
        if user.save
          log_in user
          redirect_to profile_path(user)
        else
          redirect_to root_path
        end
      else
          redirect_to root_path
      end
  end

  def update
      redirect_to root_path unless valid_user_check
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path
  end

  def show
      redirect_to root_path unless valid_user_check
      
  end

  def edit
      redirect_to root_path unless valid_user_check
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  		if current_user
  			redirect_to profile_path(current_user)
  		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clues_helper.rb
module CluesHelper
end

app/helpers/hunts_helper.rb
module HuntsHelper
	
end

app/helpers/scavenger_hunt_helper.rb
module ScavengerHuntHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
	    session[:user_id] = user.id
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def current_hunts
		current_user.scavenger_hunts
	end

	def my_hunts
		current_user.hunts
	end

	def valid_user_check
		return true if current_user
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clues/destroy.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<h1>Clues#destroy</h1>
<p>Find me in app/views/clues/destroy.html.erb</p>

app/views/clues/edit.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<h1>Clues#edit</h1>
<p>Find me in app/views/clues/edit.html.erb</p>

app/views/clues/new.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<h1>Clues#new</h1>
<p>Find me in app/views/clues/new.html.erb</p>

app/views/clues/show.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<h1>Clues#show</h1>
<p>Find me in app/views/clues/show.html.erb</p>

app/views/hunts/edit.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<p>Find me in app/views/hunts/edit.html.erb</p>

app/views/hunts/index.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>

<div id="page_body" class="debugger text-center">
	<div id="all_valid_hunts" class="debugger text-center scroll-y">
		<% if @hunts.length > 0 %>
			<ul>
			<% @hunts.each do |hunt| %>
				<li><%= link_to "Hunt", hunt_path(hunt) %></li>
			<% end %>
		<% end %>
			</ul>
	</div>
</div>

app/views/hunts/my_hunts.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>

app/views/hunts/new.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>

<%= javascript_include_tag "gmap" %>

<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>



<div id="map-container">
	<div id="panel">
	      <input onclick="clearMarkers();" type=button value="Hide Markers">
	      <input onclick="showMarkers();" type=button value="Show All Markers">
	      <input onclick="deleteMarkers();" type=button value="Delete Markers">
	</div>
	<div id="map-canvas"></div>
</div>

app/views/hunts/show.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
	

<script type ="text/javascript">
	$(document).ready(
        function initialize()
        {
        var lat = <%= @hunt.latitude %>;
        var lng = <%= @hunt.longitude %>;
        var myCenter=new google.maps.LatLng(lat,lng);

        var mapProp = {
          center:myCenter,
          zoom:10,
          mapTypeId:google.maps.MapTypeId.ROADMAP
          };

          map = new google.maps.Map(document.getElementById("map-canvas"),mapProp);

          var theHunt = new google.maps.Circle({
            center:myCenter,
            radius:2000,
            strokeColor:"#0000FF",
            strokeOpacity:0.8,
            strokeWeight:2,
            fillColor:"#0000FF",
            fillOpacity:0.4
          });

          google.maps.event.addListener(map, 'click', function(event) {
            placeMarker(event.latLng);
          });
          console.log("You are accessing the invidiual hunt script")
     
          theHunt.setMap(map)
      }
  )
</script>


<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>


<div id="page_body" class='debugger'>
	<div id="show_hunt" class="debugger">
		

			<div id="map-container">
			  <div id="map-canvas"></div>
			</div>

		<%= button_to 'Begin Hunt?', start_new_hunt_path(current_user, @hunt), method: 'post' %>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scavenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scavenger_hunt/show.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
	

<script type ="text/javascript">

   	$(document).ready(
           function initialize() {
               var lat = <%= @hunt.latitude %>;
               var lng = <%= @hunt.longitude %>;
               var myCenter=new google.maps.LatLng(lat,lng);

               var mapProp = {
                 center:myCenter,
                 zoom:10,
                 mapTypeId:google.maps.MapTypeId.ROADMAP
                 };

                 map = new google.maps.Map(document.getElementById("map-canvas"),mapProp);

                 var theHunt = new google.maps.Circle({
                   center:myCenter,
                   radius:2000,
                   strokeColor:"#0000FF",
                   strokeOpacity:0.8,
                   strokeWeight:2,
                   fillColor:"#0000FF",
                   fillOpacity:0.4
                 });
                 console.log("You are accessing the invidiual hunt script")
                 theHunt.setMap(map)
         }
     )
</script>

<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>


<div id="map-container" class="debugger">
	This is <b><%= @hunt.user.username %></b>'s hunt! which was made on <%= @hunt.user.created_at %>
	<div id="map-canvas" class="debugger">
	</div>
</div>

app/views/users/edit.html.erb
<div id="banner" class="debugger">
	<h1>Greetings <%= current_user.username %></h1>
	<span><%= link_to "home", profile_path(current_user) %></span>
	<span><%= link_to "edit profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path(current_user), {class: "button", method: "delete", action: "destroy" } %></span>
</div>

<h2> YOU ARE IN THE EDIT PROFILE PAGE</h2>

app/views/users/show.html.erb
<div id="banner" class="debugger">
	<span style="font-size: 35px;">Greetings <%= current_user.username %></span>
	<span><%= link_to "Edit Profile", edit_profile_path(current_user) %></span>
	<span><%= link_to "logout", logout_path, {class: "button", method: "delete", action: "destroy" } %></span>
</div>


<div id="page_body" class="debugger text-center">
	<div id="current_hunts" class="debugger scroll-y">
		<h3 class="text-center"><u>MY CURRENT HUNTS</u></h3>

		<% if current_hunts.length > 0 %>
			<ul>
			<% current_hunts.each do |hunt| %>
				<li><%= link_to 'example', user_scavenger_hunt_path(current_user, hunt) %></li>
			<% end %>
		<% end %>
			</ul>
	
	</div>

	<div id="my_hunts" class="debugger scroll-y">
		<h3 class="text-center"><u>MY MADE HUNTS</u></h3>
			<% if my_hunts.length > 0 %>
				<ul>
				<% my_hunts.each do |hunt| %>
					<li><%= link_to 'example', hunt_path( hunt) %></li>
				<% end %>
			<% end %>
				</ul>

	</div>
</div>

<div id="edit-body" class="debugger">
	<%= link_to "Look For New Hunt", hunts_path, {class: "button"} %><br>
	
	<%= link_to "Create New Hunt",  new_hunt_path, {class: "button"}%>

</div>

app/views/welcome/index.html.erb
<div id="banner" class="debugger">
	<h1>Welcome to <span>SCAVENGERS</span></h1>

	<span id="login" class="debugger">
		<%= form_for(:session, url: login_path) do |f|%>
				  
		username: <%= f.text_field :username %>
		    
		password: <%= f.password_field :password %>

		<%= f.submit "Login" %>
		<% end %>
	</span>
</div>

<hr>

<div id="page_body" class="debugger">

	<div id="empty-div-landing-page">

	</div>

	<div id="sign-up" class="debugger div-center">
		<div id="sign-up-form" class="debugger">
			<%= form_for(:new_user, url: sign_up_path) do |f| %>

			First Name: <%= f.text_field :first_name %>

			Last Name: <%= f.text_field :last_name %>

			Username: <%= f.text_field :username %>
			
			Email: <%= f.text_field :email %>

			Password: <%= f.password_field :password %>

			Confirm password: <%= f.password_field :confirm_password %>

			<%= f.submit "Submit" %>

			<% end %>
		</div>

	</div>
</div>